// Structure data. `sub` = sidebar subtitle, `dot` = sidebar swatch colour.
export const ANATOMY = {
  cornea: { name: "Cornea", sub: "Transparent front layer", group: "Anterior Segment", dot: "#4fc3ff",
    type: "Avascular refractive tissue", location: "Front of the globe", fn: "Provides ~2/3 of the eye's focusing power",
    clinical: "Keratoconus, ulcers, refractive surgery", related: ["sclera", "anteriorChamber", "iris"],
    overview: "The cornea is the clear, dome-shaped front window of the eye. It refracts incoming light and, together with the tear film, forms the first optical surface of the eye.",
    key: "Corneal clarity depends on its avascular, regularly arranged collagen and a healthy endothelial pump." },
  sclera: { name: "Sclera", sub: "White outer layer", group: "Outer Coat", dot: "#f1eeea",
    type: "Dense collagenous coat", location: "Outer wall of the globe", fn: "Protects the eye and anchors muscles",
    clinical: "Scleritis, trauma, scleral buckling", related: ["cornea", "choroid", "rectusMuscles"],
    overview: "The sclera is the tough, white, fibrous outer coat that maintains the shape of the globe and provides attachment for the extraocular muscles.",
    key: "The limbus (cornea–sclera junction) is the key surgical landmark for cataract and glaucoma procedures." },
  conjunctiva: { name: "Conjunctiva", sub: "Outer membrane", group: "Outer Coat", dot: "#f08ab0",
    type: "Mucous membrane", location: "Over the anterior sclera", fn: "Lubricates and protects the ocular surface",
    clinical: "Conjunctivitis, pterygium, subconjunctival bleed", related: ["sclera", "cornea"],
    overview: "The conjunctiva is a thin, vascular, transparent membrane covering the anterior sclera and lining the eyelids.",
    key: "Its fine vessels are what make the 'red eye' visible in inflammation." },
  anteriorChamber: { name: "Anterior Chamber", sub: "Fluid filled space", group: "Anterior Segment", dot: "#7fb2ff",
    type: "Aqueous-filled space", location: "Between cornea and iris", fn: "Holds aqueous humor, maintains IOP",
    clinical: "Angle closure, hyphema, uveitis cells", related: ["cornea", "iris", "trabecular"],
    overview: "The anterior chamber is the space between the back of the cornea and the front of the iris, filled with aqueous humor.",
    key: "A shallow anterior chamber is a risk factor for angle-closure glaucoma." },
  iris: { name: "Iris", sub: "Controls pupil size", group: "Uvea", dot: "#3fa0d8",
    type: "Pigmented muscular diaphragm", location: "In front of the lens", fn: "Regulates light entering the eye",
    clinical: "Iritis, iris coloboma, IOL fixation", related: ["pupil", "ciliaryBody", "lens"],
    overview: "The iris is the coloured diaphragm of the eye. Its sphincter and dilator muscles change pupil size to control how much light reaches the retina.",
    key: "Pupil dilation quality directly affects phaco and IOL implantation safety." },
  pupil: { name: "Pupil", sub: "Light opening", group: "Anterior Segment", dot: "#1b1f27",
    type: "Aperture", location: "Centre of the iris", fn: "Lets light through to the lens",
    clinical: "RAPD, anisocoria, small pupil in surgery", related: ["iris", "lens"],
    overview: "The pupil is the central opening of the iris. It acts like a camera aperture, constricting in bright light and dilating in dim light.",
    key: "Pupil reactions are a quick bedside test of the optic nerve pathway." },
  lens: { name: "Lens", sub: "Focuses light", group: "Lens", dot: "#d8c9a8",
    type: "Biconvex crystalline lens", location: "Behind iris, held by zonules", fn: "Fine focusing (accommodation)",
    clinical: "Cataract, presbyopia, IOL replacement", related: ["zonules", "ciliaryBody", "iris"],
    overview: "The crystalline lens is a transparent, biconvex structure that changes shape to focus light on the retina.",
    key: "Cataract surgery replaces the opacified lens with an IOL placed in the capsular bag." },
  zonules: { name: "Zonular Fibers", sub: "Suspensory ligaments", group: "Lens", dot: "#dfe7ef",
    type: "Fibrillin fibres", location: "Ciliary body to lens equator", fn: "Suspend the lens and transmit accommodation",
    clinical: "Zonular dehiscence, pseudoexfoliation, Marfan", related: ["lens", "ciliaryBody"],
    overview: "Zonular fibers are fine suspensory ligaments that run from the ciliary processes to the lens capsule equator.",
    key: "Weak zonules (e.g. pseudoexfoliation) need capsular tension rings during cataract surgery." },
  ciliaryBody: { name: "Ciliary Body", sub: "Produces aqueous humor", group: "Uvea", dot: "#e0525a",
    type: "Muscular and secretory tissue", location: "Behind the iris root", fn: "Makes aqueous, controls accommodation",
    clinical: "Cyclodestruction, ciliary block glaucoma", related: ["zonules", "iris", "lens"],
    overview: "The ciliary body contains the ciliary muscle for accommodation and the ciliary processes that secrete aqueous humor.",
    key: "Glaucoma drugs like beta-blockers work by reducing aqueous production here." },
  trabecular: { name: "Trabecular Meshwork", sub: "Fluid drainage", group: "Drainage", dot: "#56e0ff",
    type: "Porous filter tissue", location: "Iridocorneal angle", fn: "Filters aqueous into Schlemm's canal",
    clinical: "Open-angle glaucoma, SLT, MIGS", related: ["schlemm", "anteriorChamber"],
    overview: "The trabecular meshwork is a spongy tissue in the drainage angle through which most aqueous humor leaves the eye.",
    key: "Increased resistance in the meshwork is the main cause of raised IOP in open-angle glaucoma." },
  schlemm: { name: "Canal of Schlemm", sub: "Drains aqueous humor", group: "Drainage", dot: "#39b8ff",
    type: "Venous channel", location: "Iridocorneal angle", fn: "Drains aqueous humor",
    clinical: "Important in glaucoma", related: ["trabecular", "sclera"],
    overview: "The Canal of Schlemm is a circular channel located at the iridocorneal angle. It collects aqueous humor from the trabecular meshwork and drains it into the episcleral veins, helping to maintain intraocular pressure (IOP).",
    key: "Impaired outflow through the trabecular meshwork or Canal of Schlemm can lead to increased intraocular pressure, a major risk factor for glaucoma." },
  posteriorChamber: { name: "Posterior Chamber", sub: "Behind the iris", group: "Anterior Segment", dot: "#6f8cff",
    type: "Aqueous-filled space", location: "Between iris and lens", fn: "Receives aqueous from ciliary body",
    clinical: "Pupillary block, sulcus IOL", related: ["iris", "lens", "ciliaryBody"],
    overview: "The posterior chamber is the narrow space behind the iris and in front of the lens where aqueous humor is first secreted.",
    key: "Aqueous flows from here through the pupil into the anterior chamber." },
  vitreous: { name: "Vitreous Humor", sub: "Gel filled cavity", group: "Posterior Segment", dot: "#5fd3f0",
    type: "Transparent gel", location: "Between lens and retina", fn: "Maintains globe shape, transmits light",
    clinical: "Floaters, PVD, vitreous haemorrhage", related: ["retina", "lens"],
    overview: "The vitreous humor is a clear gel filling the large cavity behind the lens, making up about 80% of the eye's volume.",
    key: "Posterior vitreous detachment can cause retinal tears — sudden floaters need a dilated exam." },
  retina: { name: "Retina", sub: "Light sensing layer", group: "Posterior Segment", dot: "#ff7a3c",
    type: "Neurosensory tissue", location: "Inner lining of the posterior eye", fn: "Converts light into nerve signals",
    clinical: "Diabetic retinopathy, detachment, ARMD", related: ["macula", "opticDisc", "choroid"],
    overview: "The retina is the thin neural layer lining the back of the eye. Photoreceptors convert light into electrical signals sent to the brain.",
    key: "OCT and fundus imaging are the core tools to assess retinal disease." },
  choroid: { name: "Choroid", sub: "Vascular layer", group: "Uvea", dot: "#c04070",
    type: "Vascular pigmented layer", location: "Between sclera and retina", fn: "Nourishes the outer retina",
    clinical: "Choroiditis, CNV, choroidal melanoma", related: ["retina", "sclera"],
    overview: "The choroid is a richly vascular layer between the sclera and retina that supplies oxygen and nutrients to the photoreceptors.",
    key: "Abnormal choroidal vessels (CNV) are the hallmark of wet macular degeneration." },
  opticNerve: { name: "Optic Nerve", sub: "Sends signals to brain", group: "Neural", dot: "#f2a93b",
    type: "Cranial nerve II", location: "Exits the back of the globe", fn: "Carries visual signals to the brain",
    clinical: "Glaucomatous cupping, optic neuritis", related: ["opticDisc", "retina"],
    overview: "The optic nerve carries over a million ganglion-cell axons from the retina to the brain.",
    key: "Glaucoma damages the optic nerve — IOP control protects it." },
  macula: { name: "Macula", sub: "Central vision", group: "Posterior Segment", dot: "#ff9a3c",
    type: "Specialised retina", location: "Temporal to the optic disc", fn: "Sharp central and colour vision",
    clinical: "ARMD, macular oedema, macular hole", related: ["retina", "opticDisc"],
    overview: "The macula is the central part of the retina, with the fovea at its centre providing the sharpest vision.",
    key: "Macular OCT is the standard for monitoring anti-VEGF treatment." },
  opticDisc: { name: "Optic Disc", sub: "Blind spot", group: "Neural", dot: "#ff6a3a",
    type: "Nerve head", location: "Nasal posterior pole", fn: "Exit point of nerve fibres and vessels",
    clinical: "Cup-to-disc ratio, papilloedema", related: ["opticNerve", "retina"],
    overview: "The optic disc is where the optic nerve fibres and central retinal vessels leave the eye. It has no photoreceptors, creating the blind spot.",
    key: "An enlarging cup-to-disc ratio is a key sign of glaucoma progression." },
  rectusMuscles: { name: "Extraocular Muscles", sub: "Move the eye", group: "Outer Coat", dot: "#c83a3a",
    type: "Skeletal muscle", location: "Attached to the sclera", fn: "Rotate the globe",
    clinical: "Strabismus, nerve palsies", related: ["sclera"],
    overview: "Six extraocular muscles attach to the sclera and move the eye precisely in all directions.",
    key: "Muscle insertions lie a few mm behind the limbus — relevant for strabismus surgery." },
};

export const LIST_ORDER = ["cornea", "sclera", "conjunctiva", "anteriorChamber", "iris", "pupil", "lens", "zonules",
  "ciliaryBody", "trabecular", "schlemm", "posteriorChamber", "vitreous", "retina", "choroid", "opticNerve",
  "macula", "opticDisc", "rectusMuscles"];

export const SYSTEMS = {
  "Optical System": ["cornea", "anteriorChamber", "pupil", "lens", "vitreous"],
  "Uveal Tract": ["iris", "ciliaryBody", "choroid"],
  "Aqueous Outflow": ["ciliaryBody", "posteriorChamber", "trabecular", "schlemm"],
  "Neural Pathway": ["retina", "macula", "opticDisc", "opticNerve"],
  "Support & Movement": ["sclera", "conjunctiva", "zonules", "rectusMuscles"],
};

export const CLINICAL = {
  "Glaucoma": ["trabecular", "schlemm", "opticNerve", "opticDisc"],
  "Cataract & IOL": ["lens", "zonules", "iris", "cornea"],
  "Retina": ["retina", "macula", "choroid", "vitreous"],
  "Cornea & Refractive": ["cornea", "conjunctiva"],
};
